import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { getSession, hasPermission, isAdmin } from '@/lib/auth';
import { authorizeWorkOrderPlant } from '@/lib/plant-auth-helpers';
import { canManageWorkOrder, canViewWorkOrder } from '@/services/workOrderAccess.service';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = getSession(request);
    if (!session) {
      return NextResponse.json({ success: false, error: 'Not authenticated' }, { status: 401 });
    }

    const { id } = await params;
    const plantAuth = await authorizeWorkOrderPlant(request, session, id);
    if (!plantAuth.ok) return plantAuth.response;

    const wo = await db.workOrder.findUnique({
      where: { id },
      include: {
        teamMembers: { select: { userId: true } },
        maintenanceRequest: { select: { requestedBy: true } },
        pmSchedule: {
          include: {
            template: {
              include: {
                tasks: {
                  where: { isActive: true },
                  orderBy: { taskNumber: 'asc' },
                },
              },
            },
          },
        },
      },
    });

    if (!wo) {
      return NextResponse.json({ success: false, error: 'Work order not found' }, { status: 404 });
    }

    if (!canViewWorkOrder(session, wo)) {
      return NextResponse.json(
        { success: false, error: 'Access denied — you are not part of this work order workflow' },
        { status: 403 },
      );
    }

    const existingTasks = await db.workOrderTaskExecution.findMany({
      where: { workOrderId: id },
      orderBy: { taskNumber: 'asc' },
      include: {
        completedBy: { select: { id: true, fullName: true, username: true } },
      },
    });

    // Template task materialization is deterministic and limited to a user who
    // has already passed strict plant + workflow-relationship authorization.
    if (existingTasks.length === 0 && wo.pmSchedule?.template?.tasks && wo.pmSchedule.template.tasks.length > 0) {
      const templateTasks = wo.pmSchedule.template.tasks;
      const createData = templateTasks.map((tt) => ({
        workOrderId: id,
        templateTaskId: tt.id,
        taskNumber: tt.taskNumber,
        description: tt.description,
        taskType: tt.taskType,
        requiredParts: tt.requiredParts,
        estimatedMinutes: tt.estimatedMinutes,
        status: 'pending' as const,
      }));

      await db.workOrderTaskExecution.createMany({ data: createData, skipDuplicates: true });

      const tasks = await db.workOrderTaskExecution.findMany({
        where: { workOrderId: id },
        orderBy: { taskNumber: 'asc' },
        include: {
          completedBy: { select: { id: true, fullName: true, username: true } },
        },
      });

      return NextResponse.json({
        success: true,
        data: tasks,
        meta: { source: 'template', templateTitle: wo.pmSchedule.template.title, autoGenerated: true },
      });
    }

    return NextResponse.json({
      success: true,
      data: existingTasks,
      meta: existingTasks.length > 0 ? { source: 'existing' } : { source: 'none' },
    });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Failed to fetch task checklist';
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = getSession(request);
    if (!session) {
      return NextResponse.json({ success: false, error: 'Not authenticated' }, { status: 401 });
    }

    if (!hasPermission(session, 'work_orders.update') && !isAdmin(session)) {
      return NextResponse.json({ success: false, error: 'Forbidden' }, { status: 403 });
    }

    const { id } = await params;
    const plantAuth = await authorizeWorkOrderPlant(request, session, id);
    if (!plantAuth.ok) return plantAuth.response;

    const body = await request.json();
    const { description, taskType, requiredParts, estimatedMinutes, taskNumber } = body;

    if (!description || typeof description !== 'string' || description.trim().length === 0) {
      return NextResponse.json({ success: false, error: 'Task description is required' }, { status: 400 });
    }

    const wo = await db.workOrder.findUnique({
      where: { id },
      select: {
        id: true,
        status: true,
        isLocked: true,
        assignedSupervisorId: true,
        plannerId: true,
      },
    });
    if (!wo) {
      return NextResponse.json({ success: false, error: 'Work order not found' }, { status: 404 });
    }

    if (!canManageWorkOrder(session, wo)) {
      return NextResponse.json(
        { success: false, error: 'Only the assigned supervisor/planner or maintenance management can add work-order tasks' },
        { status: 403 },
      );
    }

    if (wo.isLocked || wo.status === 'verified' || wo.status === 'closed') {
      return NextResponse.json({ success: false, error: 'Work order has been reviewed. Task changes are no longer allowed. Status: ' + wo.status }, { status: 400 });
    }

    let nextTaskNumber = taskNumber;
    if (!nextTaskNumber) {
      const lastTask = await db.workOrderTaskExecution.findFirst({
        where: { workOrderId: id },
        orderBy: { taskNumber: 'desc' },
      });
      nextTaskNumber = (lastTask?.taskNumber ?? 0) + 1;
    }

    const validTaskTypes = ['check', 'measure', 'inspect', 'lubricate', 'replace', 'record'];
    const finalTaskType = taskType && validTaskTypes.includes(taskType) ? taskType : 'check';

    const task = await db.workOrderTaskExecution.create({
      data: {
        workOrderId: id,
        taskNumber: nextTaskNumber,
        description: description.trim(),
        taskType: finalTaskType,
        requiredParts: requiredParts ? JSON.stringify(requiredParts) : null,
        estimatedMinutes: estimatedMinutes ? parseInt(String(estimatedMinutes), 10) : null,
        status: 'pending',
      },
      include: {
        completedBy: { select: { id: true, fullName: true, username: true } },
      },
    });

    await db.auditLog.create({
      data: {
        userId: session.userId,
        action: 'create',
        entityType: 'wo_task_execution',
        entityId: task.id,
        newValues: JSON.stringify({
          workOrderId: id,
          taskNumber: nextTaskNumber,
          description: description.trim(),
          taskType: finalTaskType,
        }),
      },
    });

    return NextResponse.json({ success: true, data: task }, { status: 201 });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Failed to create task';
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}
