import { PrismaClient } from '@prisma/client';
if (!process.env.DATABASE_URL || !/^postgres(?:ql)?:\/\//i.test(process.env.DATABASE_URL)) throw new Error('DATABASE_URL must point to PostgreSQL');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { createAdapter } = require('../src/lib/create-postgres-adapter');
const db=new PrismaClient({adapter:createAdapter(process.env.DATABASE_URL)});
const TAG='UAT-GTP-312-1-027',PREFIX='GTP-SING';
const RULES=[
{key:'sewing',code:'CMP-SEW',re:/sewing machine|sawing machine|pegasus|pegases/i},{key:'needle',code:'PRT-NEEDLE',re:/needle/i},{key:'sew-cable',code:'PRT-SEW-CABLE',re:/sewing machine cable/i},{key:'sew-socket',code:'PRT-SEW-SOCKET',re:/sewing machine socket/i},{key:'sew-blade',code:'PRT-SEW-BLADE',re:/sewing machine blade/i},
{key:'piler',code:'CMP-PILER',re:/piler|piller|piler unit|main piler|main piller/i},{key:'piler-chain',code:'PRT-PILER-CHAIN',re:/piling chain|piler chain/i},{key:'piler-belt',code:'PRT-PILER-BELT',re:/piler motor belt/i},{key:'piler-gear',code:'PRT-PILER-GEAR',re:/piler gear|piller gear/i},{key:'plaiter',code:'CMP-PLAIT',re:/plaiter|j-box/i},
{key:'burner',code:'CMP-BURNER',re:/burner|burnner/i},{key:'gas',code:'SUB-GAS',re:/gas.*flow|gas supply|reduction valve/i},
{key:'mangle',code:'CMP-MANGLE',re:/\bmangle\b/i},{key:'saturator',code:'CMP-SAT',re:/saturator/i},{key:'washer',code:'CMP-WASH',re:/1st washer|first washer|washing unit/i},{key:'spray',code:'CMP-SPRAY',re:/spray unit|splickling water|sprinkling water/i},{key:'desize',code:'CMP-DESIZE',re:/desizing tank|desilting tank/i},
{key:'water',code:'PRT-WATER-LINE',re:/water coupling|water leakage|water line|water hose|water pipe/i},{key:'air',code:'SUB-AIR',re:/air leakage/i},{key:'steam',code:'SUB-STEAM',re:/steam supply|steam line/i},
{key:'guider',code:'CMP-GUIDER',re:/cloth guider|foxwell guider|foxwell quider/i},{key:'pin',code:'CMP-PIN',re:/pin rollers?/i},{key:'brush',code:'CMP-BRUSH',re:/brush mechanism/i},{key:'roller',code:'CMP-ROLLER',re:/bummer roller|rollers? on the singeing|faulty bearing on the singeing/i},
{key:'lifter',code:'CMP-LIFTER',re:/\blifter\b|pallet lifter/i},{key:'poteye',code:'CMP-POTEYE',re:/pot[- ]?eye|port eye/i},
{key:'hydrant',code:'CMP-HYDRANT',re:/fire hydrant|fire extinguisher.*water|emergency fire extinguisher/i},{key:'fire-hose',code:'PRT-FIRE-HOSE',re:/fire.*hose/i},{key:'estop',code:'CMP-ESTOP',re:/emergency stop/i},
{key:'yard',code:'INS-YARD',re:/yardage counter/i},{key:'level',code:'INS-LEVEL',re:/level sensor/i},{key:'electrical',code:'CMP-ELEC',re:/electrical fault/i},{key:'drive',code:'CMP-DRIVE',re:/unable to move|machine unable to move/i},{key:'wheels',code:'CMP-WHEELS',re:/lubricate wheels/i}
] as const;
const MARKER='Auto-mapped from GTP Singeing Machine historical work-order title by conservative UAT commissioning rule; verify against OEM/master-data before production approval.';
function full(c:string){return `${PREFIX}-${c}`;}
async function main(){const asset=await db.asset.findUnique({where:{assetTag:TAG},select:{id:true,assetTag:true,name:true}});if(!asset)throw new Error('Singeing missing');const comps=await db.componentRegistry.findMany({where:{assetId:asset.id,componentCode:{in:RULES.map(r=>full(r.code))}},select:{id:true,componentCode:true}});const map=new Map(comps.map(c=>[c.componentCode,c.id]));for(const r of RULES)if(!map.has(full(r.code)))throw new Error(`Missing ${full(r.code)}`);
const wos=await db.workOrder.findMany({where:{assetId:asset.id},select:{id:true,title:true}});let matched=0,links=0;const counts:Record<string,number>={};await db.$transaction(async tx=>{for(const wo of wos){const title=wo.title||'';const ms=RULES.filter(r=>r.re.test(title));if(!ms.length)continue;matched++;for(const r of ms){await tx.workOrderComponent.upsert({where:{workOrderId_componentRegistryId:{workOrderId:wo.id,componentRegistryId:map.get(full(r.code))!}},update:{notes:`${MARKER} Rule=${r.key}; source title: ${title}`},create:{workOrderId:wo.id,componentRegistryId:map.get(full(r.code))!,notes:`${MARKER} Rule=${r.key}; source title: ${title}`}});links++;counts[r.key]=(counts[r.key]||0)+1;}}});console.log(JSON.stringify({asset,totalWorkOrders:wos.length,matchedWorkOrders:matched,coveragePct:Number((matched/wos.length*100).toFixed(1)),upsertedLinks:links,ruleLinks:counts},null,2));}
main().catch(e=>{console.error(e);process.exit(1)}).finally(async()=>db.$disconnect());