import { PrismaClient } from '@prisma/client';
if (!process.env.DATABASE_URL || !/^postgres(?:ql)?:\/\//i.test(process.env.DATABASE_URL)) throw new Error('DATABASE_URL must point to PostgreSQL');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { createAdapter } = require('../src/lib/create-postgres-adapter');
const db=new PrismaClient({adapter:createAdapter(process.env.DATABASE_URL)});
const TAG='UAT-GTP-310-1-004',PREFIX='GTP-BLR';
const RULES=[
{key:'sat1',code:'CMP-SAT1',re:/1st saturator|first saturator|saturator 1/i},{key:'sat2',code:'CMP-SAT2',re:/2nd saturator|second saturator/i},{key:'sat-mangle',code:'CMP-SAT1-MANGLE',re:/saturator.*mangle|squeezer.*saturator/i},{key:'sat-bowl',code:'CMP-SAT1-BOWL',re:/saturator.*bowl|squeezer bowl.*saturator/i},
{key:'washer1',code:'SUB-WASH1',re:/washer\s*#?\s*1|1st washer|first washer|washing tank 1/i},{key:'washer2',code:'SUB-WASH2',re:/washer\s*#?\s*2|2nd washer|second washer|washing unit 2/i},{key:'washer3',code:'SUB-WASH3',re:/washer\s*#?\s*3|3rd washer|third washer/i},
{key:'jbox1',code:'SUB-J1',re:/j[ .-]?box\s*1|1st j[ .-]?box|first j[ .-]?box/i},{key:'jbox2',code:'SUB-J2',re:/j[ .-]?box\s*2|2nd j[ .-]?box/i},{key:'jbox-overflow',code:'CMP-J1-OVERFLOW',re:/j\\.?\\s*box\\s*1.*overflow|caustic overflow|caustic outlet/i},{key:'jbox-panel',code:'CMP-J1-PANEL',re:/j[ .-]?box panel/i},
{key:'piler',code:'CMP-PILER',re:/piler|piller/i},{key:'sewing',code:'CMP-SEW',re:/sewing machine/i},{key:'needle',code:'PRT-NEEDLE',re:/sewing machine needle|broken.*needle/i},
{key:'air',code:'CMP-AIR-LINE',re:/air leakage|air line/i},{key:'steam',code:'CMP-STEAM-LINE',re:/steam supply|steam leakage|steam line/i},{key:'water',code:'CMP-WATER-LINE',re:/water leakage|water line|water pipe|drain line|water seepage/i},{key:'chemical',code:'CMP-CHEM-PUMP',re:/chemical pump/i},{key:'solenoid',code:'CMP-SOL-VALVE',re:/solenoid valve/i},
{key:'chain',code:'CMP-CHAIN',re:/\bchain\b|chains|chain drive/i},{key:'coupling',code:'CMP-COUPLING',re:/coupling|coppling/i},{key:'gearbox',code:'CMP-GEARBOX',re:/gearbox|gear box/i},{key:'motor',code:'CMP-MOTOR',re:/\bmotor\b/i},{key:'bearing',code:'PRT-BEAR',re:/bearings?/i},{key:'shaft',code:'PRT-SHAFT',re:/shaft/i},
{key:'roller',code:'CMP-GUIDE-ROLLER',re:/guide roller|rollers?/i},{key:'grip',code:'CMP-GRIP-TAPE',re:/grip tape|gripe tape/i},{key:'temp',code:'INS-W2-TEMP',re:/temperature.*gauge|temprature.*gauge/i},{key:'yard',code:'INS-W3-YARD',re:/yards? counter/i},
{key:'pot',code:'CMP-POT',re:/pot meter/i},{key:'comp-switch',code:'CMP-COMP-SW',re:/compensator switch/i},{key:'reservoir',code:'CMP-RESERVOIR',re:/water reservior|water reservoir|reservoir coverings/i},{key:'j1-mangle',code:'CMP-J1-MANGLE',re:/1st box mangle|1st j\\.?\\s*box.*mangle/i},{key:'panel',code:'CMP-PANEL',re:/panel not responding|control panel/i},{key:'light',code:'CMP-LIGHT',re:/dead bulb|bulbs?/i},{key:'eyewash',code:'CMP-EYEWASH',re:/eye washer|eye wash/i}
] as const;
const MARKER='Auto-mapped from GTP Bleaching Range historical work-order title by conservative UAT commissioning rule; verify against OEM/master-data before production approval.';
function full(c:string){return `${PREFIX}-${c}`;}
async function main(){const asset=await db.asset.findUnique({where:{assetTag:TAG},select:{id:true,assetTag:true,name:true}});if(!asset)throw new Error('Bleaching Range missing');const comps=await db.componentRegistry.findMany({where:{assetId:asset.id,componentCode:{in:RULES.map(r=>full(r.code))}},select:{id:true,componentCode:true}});const map=new Map(comps.map(c=>[c.componentCode,c.id]));for(const r of RULES)if(!map.has(full(r.code)))throw new Error(`Missing ${full(r.code)}`);const wos=await db.workOrder.findMany({where:{assetId:asset.id},select:{id:true,title:true}});let matched=0,links=0;const counts:Record<string,number>={};await db.$transaction(async tx=>{for(const wo of wos){const title=wo.title||'';const ms=RULES.filter(r=>r.re.test(title));if(!ms.length)continue;matched++;for(const r of ms){await tx.workOrderComponent.upsert({where:{workOrderId_componentRegistryId:{workOrderId:wo.id,componentRegistryId:map.get(full(r.code))!}},update:{notes:`${MARKER} Rule=${r.key}; source title: ${title}`},create:{workOrderId:wo.id,componentRegistryId:map.get(full(r.code))!,notes:`${MARKER} Rule=${r.key}; source title: ${title}`}});links++;counts[r.key]=(counts[r.key]||0)+1;}}});console.log(JSON.stringify({asset,totalWorkOrders:wos.length,matchedWorkOrders:matched,coveragePct:Number((matched/wos.length*100).toFixed(1)),upsertedLinks:links,ruleLinks:counts},null,2));}
main().catch(e=>{console.error(e);process.exit(1)}).finally(async()=>db.$disconnect());